# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\code\semestrovaya\ui\details_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailsDialog(object):
    def setupUi(self, DetailsDialog):
        DetailsDialog.setObjectName("DetailsDialog")
        DetailsDialog.resize(420, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(DetailsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageLabel = QtWidgets.QLabel(DetailsDialog)
        self.imageLabel.setMinimumSize(QtCore.QSize(320, 240))
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.detailsText = QtWidgets.QTextEdit(DetailsDialog)
        self.detailsText.setReadOnly(True)
        self.detailsText.setObjectName("detailsText")
        self.verticalLayout.addWidget(self.detailsText)
        self.closeButton = QtWidgets.QPushButton(DetailsDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)

        self.retranslateUi(DetailsDialog)
        QtCore.QMetaObject.connectSlotsByName(DetailsDialog)

    def retranslateUi(self, DetailsDialog):
        _translate = QtCore.QCoreApplication.translate
        DetailsDialog.setWindowTitle(_translate("DetailsDialog", "Детали"))
        self.closeButton.setText(_translate("DetailsDialog", "Закрыть"))
